live_config_reload = true

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = "#1d1f21"
blue = "#81a2be"
cyan = "#8abeb7"
green = "#b5bd68"
magenta = "#b294bb"
red = "#cc6666"
white = "#c5c8c6"
yellow = "#f0c674"

[colors.primary]
background = "#000000"
foreground = "#f4f4f4"

[cursor]
unfocused_hollow = true
vi_mode_style = "Block"

[cursor.style]
blinking = "Off"
shape = "Beam"

[font]
size = 12.0

[font.bold]
family = "0xProto Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "0xProto Nerd Font Mono"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "0xProto Nerd Font Mono"
style = "Italic"

[font.normal]
family = "0xProto Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.5

[window.padding]
x = 5
y = 5
